[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
hex = "0.4.3"
sha2 = "0.10.7"
sodiumoxide = "0.2.7"
